name: 'Install Linkerd'
description: 'installs linkerd onto target cluster'
inputs:
  KUBECONFIG:
    description: "path to kubeconfig"
    required: false
    default: "~/.kube/config"
  INSTALL_VIZ:
    description: "install viz or not"
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/install-kubectl.sh
      shell: bash
    - run: ${{ github.action_path }}/install-linkerd.sh
      shell: bash
      env:
        KUBECONFIG: ${{ inputs.KUBECONFIG }}
        INSTALL_VIZ: ${{ inputs.INSTALL_VIZ }}
